window.BizziConfig = {
  mode: "production",
  version: "V304",
  appName: "Zeyds",
  country: "Côte d'Ivoire",
  currency: "FCFA",
  official: {
    domain: "bizzi-africa.com",
    website: "https://bizzi-africa.com",
    contactEmail: "contact@bizzi-africa.com",
    supportEmail: "support@bizzi-africa.com",
    paymentEmail: "paiement@bizzi-africa.com",
    providersEmail: "prestataires@bizzi-africa.com",
    supportWhatsapp: "+225 07 59 95 81 21",
  },
  restBackend: {
    url: "https://bizzi-gateway.onrender.com",
    anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzg1NDM3NDAxLCJleHAiOjIxMDA3OTc0MDF9.rkYbqdw1bG0U5FwTmTRPDqIoCtwaNTWO35oOOKhtpwk",
  },
  supabase: {
    url: "https://hqqppxnvorcnvksulhna.supabase.co",
    anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcXBweG52b3JjbnZrc3VsaG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI3NjA1MzEsImV4cCI6MjA5ODMzNjUzMX0.pMTb34CHKpaIRjVa975JtwBsC6iouwoFxxBEbjsnYNM",
    publicProviderView: "public_provider_directory",
    storage: {
      providerPhotos: "provider-photos",
      verificationProofs: "provider-proofs",
      paymentProofs: "payment-proofs",
      eventPosters: "event-posters",
      foodPhotos: "food-photos",
      exceptionPlacePhotos: "exception-place-photos",
      requestPhotos: "request-photos",
    },
  },
  payments: {
    mode: "manual_validation",
    methods: ["Wave", "Orange Money", "MTN Money"],
    accounts: {
      "Wave": "A renseigner",
      "Orange Money": "A renseigner",
      "MTN Money": "A renseigner",
    },
    aggregator: {
      enabled: false,
      provider: "a_configurer",
      checkoutUrl: "",
      checkoutEndpoint: "https://hqqppxnvorcnvksulhna.supabase.co/functions/v1/payment-checkout",
      webhookUrl: "https://hqqppxnvorcnvksulhna.supabase.co/functions/v1/payment-webhook",
      webhookMode: "backend_only",
    },
  },
  backend: {
    adminActionsEndpoint: "https://hqqppxnvorcnvksulhna.supabase.co/functions/v1/admin-actions",
    dispatchEndpoint: "https://hqqppxnvorcnvksulhna.supabase.co/functions/v1/delivery-dispatch",
    serverAlertsEndpoint: "https://hqqppxnvorcnvksulhna.supabase.co/functions/v1/server-alerts",
  },
  observability: {
    endpoint: "https://hqqppxnvorcnvksulhna.supabase.co/functions/v1/error-ingest",
    forwarderEndpoint: "https://hqqppxnvorcnvksulhna.supabase.co/functions/v1/monitoring-forwarder",
    externalProvider: "a_configurer",
    sampleRate: 1,
  },
  realtime: {
    locationEndpoint: "https://hqqppxnvorcnvksulhna.supabase.co/functions/v1/location-live",
  },
  aiVoice: {
    enabled: true,
    provider: "openai",
    model: "gpt-4o-transcribe",
    language: "fr",
    locale: "fr-CI",
    accentMode: "africa_fr",
    maxAlternatives: 5,
    endpoint: "https://hqqppxnvorcnvksulhna.supabase.co/functions/v1/voice-transcribe",
    browserFallback: true,
  },
  notifications: {
    enabled: true,
    vapidPublicKey: "BFsmlYLLFeStWOvvaU47YXn5CKyGIsyztoxeZsOj8h4hl9WAX31ERNzrfC8wPSyr6YkyJPDca3nybcp-iLOHl-4",
    subscribeEndpoint: "https://hqqppxnvorcnvksulhna.supabase.co/functions/v1/push-subscribe",
    notifyEndpoint: "https://hqqppxnvorcnvksulhna.supabase.co/functions/v1/push-notify",
  },
  maps: {
    provider: "auto",
    mapboxAccessToken: "",
    geocodingEndpoint: "https://bizzi-backend.onrender.com",
    routingMode: "backend_first",
    fallbackProvider: "openstreetmap",
    country: "ci",
    language: "fr",
    bbox: "-8.7,4.0,-2.4,10.9",
    proximity: "-4.0244,5.3453",
  },
  integrations: {
    vapidKeyProcedure: "docs/procedures-integrations-v174.md",
    fieldTestingChecklist: "docs/tests-terrain-v302.md",
    loadTestingScript: "../load-tests/bizzi-load-scenarios.js",
    prelaunchGuide: "docs/pack-lancement-v302.md",
  },
  launch: {
    mode: "prelaunch",
    productionUnlocked: false,
  },
  admin: {
    demoPin: "",
    allowQueryEntry: false,
  },
  social: {
    whatsappCommunity: "",
    facebookPage: "",
    instagram: "",
    tiktok: "",
  },
};
