window.BizziConfig = {
  mode: "production",
  version: "V215",
  appName: "Bizzi",
  country: "Côte d'Ivoire",
  currency: "FCFA",
  official: {
    domain: "bizzi-africa.com",
    website: "https://bizzi-africa.com",
    contactEmail: "contact@bizzi-africa.com",
    supportEmail: "support@bizzi-africa.com",
    paymentEmail: "paiement@bizzi-africa.com",
    providersEmail: "prestataires@bizzi-africa.com",
    supportWhatsapp: "+225 07 59 95 81 21",
  },
  supabase: {
    url: "https://VOTRE-PROJET.supabase.co",
    anonKey: "VOTRE_CLE_PUBLISHABLE_OU_ANON_SUPABASE",
    publicProviderView: "public_provider_directory",
    storage: {
      providerPhotos: "provider-photos",
      verificationProofs: "provider-proofs",
      paymentProofs: "payment-proofs",
      eventPosters: "event-posters",
      foodPhotos: "food-photos",
    },
  },
  payments: {
    mode: "manual_validation",
    methods: ["Wave", "Orange Money", "MTN Money"],
    accounts: {
      "Wave": "+225 XX XX XX XX XX",
      "Orange Money": "+225 XX XX XX XX XX",
      "MTN Money": "+225 XX XX XX XX XX",
    },
    aggregator: {
      enabled: false,
      provider: "NOM_AGREGATEUR",
      checkoutUrl: "",
      checkoutEndpoint: "https://VOTRE-PROJET.supabase.co/functions/v1/payment-checkout",
      webhookUrl: "https://VOTRE-PROJET.supabase.co/functions/v1/payment-webhook",
      webhookMode: "backend_only",
    },
  },
  backend: {
    adminActionsEndpoint: "https://VOTRE-PROJET.supabase.co/functions/v1/admin-actions",
    dispatchEndpoint: "https://VOTRE-PROJET.supabase.co/functions/v1/delivery-dispatch",
    serverAlertsEndpoint: "https://VOTRE-PROJET.supabase.co/functions/v1/server-alerts",
  },
  observability: {
    endpoint: "https://VOTRE-PROJET.supabase.co/functions/v1/error-ingest",
    forwarderEndpoint: "https://VOTRE-PROJET.supabase.co/functions/v1/monitoring-forwarder",
    externalProvider: "SENTRY_OU_BETTER_STACK_OU_LOGTAIL",
    sampleRate: 1,
  },
  realtime: {
    locationEndpoint: "https://VOTRE-PROJET.supabase.co/functions/v1/location-live",
  },
  aiVoice: {
    enabled: true,
    provider: "openai",
    model: "gpt-4o-mini-transcribe",
    language: "fr",
    endpoint: "https://VOTRE-PROJET.supabase.co/functions/v1/voice-transcribe",
    browserFallback: true,
  },
  notifications: {
    enabled: false,
    vapidPublicKey: "VOTRE_CLE_PUBLIQUE_VAPID",
    subscribeEndpoint: "https://VOTRE-PROJET.supabase.co/functions/v1/push-subscribe",
    notifyEndpoint: "https://VOTRE-PROJET.supabase.co/functions/v1/push-notify",
  },
  maps: {
    provider: "auto",
    mapboxAccessToken: "",
    geocodingEndpoint: "https://VOTRE-PROJET.supabase.co/functions/v1/map-geocode",
    routingMode: "backend_first",
    fallbackProvider: "openstreetmap",
    country: "ci",
    language: "fr",
    bbox: "-8.7,4.0,-2.4,10.9",
    proximity: "-4.0244,5.3453",
  },
  integrations: {
    vapidKeyProcedure: "docs/procedures-integrations-v174.md",
    fieldTestingChecklist: "docs/tests-terrain-v174.md",
    loadTestingScript: "../load-tests/bizzi-load-scenarios.js",
    prelaunchGuide: "docs/pack-lancement-v181.md",
  },
  launch: {
    mode: "prelaunch",
    productionUnlocked: false,
  },
  admin: {
    demoPin: "A_REMPLACER_PAR_UN_CODE_ADMIN_TEMPORAIRE",
    allowQueryEntry: false,
  },
  social: {
    whatsappCommunity: "https://chat.whatsapp.com/VOTRE_COMMUNAUTE",
    facebookPage: "https://www.facebook.com/VOTRE_PAGE",
    instagram: "https://www.instagram.com/VOTRE_COMPTE",
    tiktok: "https://www.tiktok.com/@VOTRE_COMPTE",
  },
};
